on:
  push:
    branches:
      - 1.0
  workflow_dispatch:

jobs:
  build:
    name: 'Docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3'
        cache: 'pip'
        cache-dependency-path: 'docs/requirements.txt'
    - name: 'Build HTML documentation'
      run: make -C docs/ html
    - name: 'Upload'
      uses: actions/upload-artifact@v3
      with:
        name: doc-html
        path: docs/build/html