
name: docs

on:
  workflow_run:
    workflows: [ test ]
    types:
      - completed
  workflow_dispatch:

jobs:
  on-test-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Don't worry, everything will be fine.'
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: 'set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3'
        cache: 'pip'
        cache-dependency-path: 'docs/requirements.txt'
    - name: 'Install build dependencies'
      run: make -C docs/ venv
    - name: 'Check documentation'
      run: make -C docs/ check
    - name: 'build HTML documentation'
      run: make -C docs/ html
    - name: 'upload'
      uses: actions/upload-artifact@v3
      with:
        name: doc-html
        path: docs/build/html